image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      poetry install
      source .venv/bin/activate
      cp template.env .env
      python manage.py migrate
    command: |
      source .venv/bin/activate
      python manage.py runserver

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
    onOpen: open-preview
