# Generated by Django 4.1.2 on 2022-10-23 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_salmonrunshiftsummaryraw_salmonrunshiftdetailraw_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salmonrunshiftdetailraw",
            name="summary",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detail",
                to="app.salmonrunshiftsummaryraw",
            ),
        ),
    ]
