# Generated by Django 4.1.2 on 2022-10-23 08:00

from django.db import migrations


def set_summary(apps, schema_editor):
    SalmonRunShiftSummaryRaw = apps.get_model("app", "SalmonRunShiftSummaryRaw")
    SalmonRunShiftDetailRaw = apps.get_model("app", "SalmonRunShiftDetailRaw")
    for detail in SalmonRunShiftDetailRaw.objects.filter(summary__isnull=True):
        detail.summary = SalmonRunShiftSummaryRaw.objects.get(
            uploaded_by=detail.uploaded_by, shift_id=detail.shift_id
        )
        detail.save()


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_salmonrunshiftdetailraw_summary"),
    ]

    operations = [
        migrations.RunPython(set_summary, migrations.RunPython.noop),
    ]
