# Generated by Django 4.1.2 on 2022-10-23 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_backfill_salmonrunshiftdetailraw_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salmonrunshiftdetailraw",
            name="summary",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detail",
                to="app.salmonrunshiftsummaryraw",
            ),
        ),
    ]
