# Generated by Django 4.1.2 on 2022-10-25 08:52

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_salmonrunshiftdetailraw_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalmonRunRotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_end_time",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                ),
                ("stage", models.TextField()),
                (
                    "weapons",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="salmonrunshiftsummaryraw",
            name="rotation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.salmonrunrotation",
            ),
        ),
    ]
