# Generated by Django 4.1.2 on 2022-10-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_salmonrunrotation_salmonrunshiftsummaryraw_rotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="salmonrunshiftsummaryraw",
            name="played_at",
            field=models.DateTimeField(null=True),
        ),
    ]
