# Generated by Django 4.1.2 on 2022-10-26 04:17
import base64

import pendulum
from django.db import migrations


def set_played_at(apps, schema_editor):
    SalmonRunShiftSummaryRaw = apps.get_model("app", "SalmonRunShiftSummaryRaw")

    for summary in SalmonRunShiftSummaryRaw.objects.only("pk", "shift_id"):
        shift_id = summary.shift_id
        decoded_shift_id = base64.standard_b64decode(shift_id).decode("utf-8")
        played_at = pendulum.parse(decoded_shift_id[41:56])
        SalmonRunShiftSummaryRaw.objects.filter(pk=summary.id).update(
            played_at=played_at
        )


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_salmonrunshiftsummaryraw_played_at"),
    ]

    operations = [
        migrations.RunPython(set_played_at, migrations.RunPython.noop),
    ]
