# Generated by Django 4.1.2 on 2022-10-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_backfill_salmonrunshiftsummaryraw_played_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salmonrunshiftsummaryraw",
            name="played_at",
            field=models.DateTimeField(),
        ),
    ]
