# Generated by Django 4.1.2 on 2022-11-06 03:56

from django.db import migrations

from .. import models


def create_summaries(apps, schema_editor):
    SalmonRunShiftSummaryRaw = apps.get_model("app", "SalmonRunShiftSummaryRaw")
    SalmonRunShiftSummary = apps.get_model("app", "SalmonRunShiftSummary")
    for raw_summary in SalmonRunShiftSummaryRaw.objects.iterator():
        # noinspection PyProtectedMember
        summary = SalmonRunShiftSummary(
            **models.SalmonRunShiftSummary._from_raw(
                raw_summary.uploaded_by, raw_summary.rotation, raw_summary.data
            )
        )
        SalmonRunShiftSummary.objects.bulk_create([summary], ignore_conflicts=True)


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_salmonrunshiftsummary_and_more"),
    ]

    operations = [
        migrations.RunPython(create_summaries, migrations.RunPython.noop),
    ]
