# Generated by Django 4.1.2 on 2022-11-06 13:10

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_backfill_salmonrunshiftsummary"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalmonRunWave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("cleared", models.BooleanField()),
                ("water_level", models.IntegerField()),
                ("event", models.TextField()),
                ("golden_egg_quota", models.IntegerField()),
                ("golden_eggs_delivered", models.IntegerField()),
                (
                    "specials_used",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waves",
                        to="app.salmonrunshiftsummary",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalmonRunShiftPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("splatnet_id", models.TextField()),
                ("is_uploader", models.BooleanField()),
                ("bosses_defeated", models.IntegerField()),
                ("golden_eggs_delivered", models.IntegerField()),
                ("golden_eggs_assisted", models.IntegerField()),
                ("power_eggs_delivered", models.IntegerField()),
                ("teammates_rescued", models.IntegerField()),
                ("times_rescued", models.IntegerField()),
                ("special_weapon", models.TextField()),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="app.salmonrunshiftsummary",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalmonRunShiftDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hazard_level", models.FloatField()),
                ("smell_meter", models.IntegerField()),
                (
                    "summary",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail",
                        to="app.salmonrunshiftsummary",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="salmonrunwave",
            constraint=models.UniqueConstraint(
                fields=("shift", "number"), name="salmonrunwave_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="salmonrunshiftplayer",
            constraint=models.UniqueConstraint(
                fields=("shift", "splatnet_id"), name="salmonrunshiftplayer_unique"
            ),
        ),
    ]
