# Generated by Django 4.1.2 on 2022-12-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_alter_salmonrunshiftsummary_rotation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salmonrunshiftdetail",
            name="smell_meter",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
